---
kind: pipeline
type: ssh
name: Test

server:
  host: martha.r
  user: ci
  ssh_key:
    from_secret: SSH_KEY

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: run tests
  commands:
  # this also compiles vmsh against notos,
  # disable faulthandler so we do not run into timeouts
  - nix develop ".#devShells.x86_64-linux.ci-shell" --command pytest -p no:faulthandler -s ./tests/test_help.py
  - TEST_NO_REBUILD=1 nix develop ".#devShells.x86_64-linux.ci-shell" --command pytest -n $(nproc --ignore=2) -s ./tests
trigger:
  event:
  - push
---
kind: signature
hmac: 20e385a488f1f8e6c34db88519ec78e2c0700d2c0ca7690e30a9b92a6bafb39c

...
