---
kind: pipeline
type: ssh
name: Test

server:
  host: martha.r
  user: ci
  ssh_key:
    from_secret: SSH_KEY

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: run tests
  commands:
  # this also compiles vmsh against notos,
  # disable faulthandler so we do not run into timeouts
  - nix develop ".#devShells.x86_64-linux.ci-shell" --command pytest -p no:faulthandler -s ./tests/test_help.py
  - TEST_NO_REBUILD=1 nix develop ".#devShells.x86_64-linux.ci-shell" --command pytest -n $(nproc --ignore=2) -s ./tests
trigger:
  event:
  - push

---
kind: pipeline
type: ssh
name: Nix build

server:
  host: martha.r
  user: ci
  ssh_key:
    from_secret: SSH_KEY

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: build all nix packages
  commands:
  - nix flake check
trigger:
  event:
  - push

---
kind: signature
hmac: 8f99959ad2356b7581b5a6076dac5e56d2b3cddd6adb4d571598855dd8126b2d

...
