---
kind: pipeline
type: ssh
name: Test

server:
  host: martha.r
  user: ci
  ssh_key:
    from_secret: SSH_KEY

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: run tests
  commands:
  - nix-shell ./ci.nix --run 'pytest -s ./tests'
trigger:
  branch:
  - main
  event:
  - push
  - pull_request

---
kind: signature
hmac: 2e94c7008120a63c43aff741d60969b44d46f74db0f65bb82fde6ddaee261bf5

...
