---
kind: pipeline
type: exec
name: Packages

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: build nix packages
  commands:
  - nix flake check -L .#
  - if [[ -n "$CACHIX_SIGNING_KEY" ]]; then nix eval --raw .#checks.x86_64-linux --apply builtins.toJSON | nix shell nixpkgs#jq nixpkgs#cachix -c bash -c "jq -r 'del(.\"nixos-image\", .\"phoronix-image\", .\"measurement-image\") | to_entries[] | .value' | cachix push mic92"; fi
  environment:
    CACHIX_SIGNING_KEY:
      from_secret: cachix_signing_key
trigger:
  event:
  - push
  - pull_request
---
kind: pipeline
type: ssh
name: Test

server:
  host: wilfred.r
  user: ci
  ssh_key:
    from_secret: SSH_KEY

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: run tests
  commands:
  # this also compiles vmsh against notos,
  # disable faulthandler so we do not run into timeouts
  - nix develop ".#devShells.x86_64-linux.ci-shell" --command pytest -p no:faulthandler -s ./tests/test_help.py
  - nix build .#firecracker-example .#crosvm-example .#qemu-example .#kvmtool-example
  - TEST_NO_REBUILD=1 nix develop ".#devShells.x86_64-linux.ci-shell" --command pytest -n $(nproc --ignore=2) -s ./tests
trigger:
  event:
  - push
---
kind: signature
hmac: 4e8f88db1e870b4ae220626d48dd15d3d4bed06bc4bb320d192e9a235efdd48f

...
