---
kind: pipeline
type: ssh
name: Test

server:
  host: martha.r
  user: ci
  ssh_key:
    from_secret: SSH_KEY

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: run tests
  commands:
  # this also compiles vmsh against notos,
  # disable faulthandler so we do not run into timeouts
  - nix develop ".#ci-shell" --command pytest -p no:faulthandler -s ./tests/test_help.py
  - TEST_NO_REBUILD=1 nix develop ".#ci-shell" --command pytest -n $(nproc --ignore=2) -s ./tests
trigger:
  event:
  - push

---
kind: signature
hmac: baa543cc6c22c8851c0f71f880b0119da7aa3ccf52958836ed3e49e941f4a2e9

...
