---
kind: pipeline
type: exec
name: Packages

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: build nix packages
  commands:
  - nix flake check -L .#
  - if [[ -n "$CACHIX_SIGNING_KEY" ]]; then nix eval --raw .#checks.x86_64-linux --apply builtins.toJSON | nix shell nixpkgs#jq nixpkgs#cachix -c bash -c "jq -r 'to_entries[] | .value' | cachix push mic92"; fi
  environment:
    CACHIX_SIGNING_KEY:
      from_secret: cachix_signing_key
trigger:
  event:
  - push
  - pull_request
---
kind: pipeline
type: ssh
name: Test

server:
  host: martha.r
  user: ci
  ssh_key:
    from_secret: SSH_KEY

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: run tests
  commands:
  # this also compiles vmsh against notos,
  # disable faulthandler so we do not run into timeouts
  - nix develop ".#devShells.x86_64-linux.ci-shell" --command pytest -p no:faulthandler -s ./tests/test_help.py
  - TEST_NO_REBUILD=1 nix develop ".#devShells.x86_64-linux.ci-shell" --command pytest -n $(nproc --ignore=2) -s ./tests
trigger:
  event:
  - push
---
kind: signature
hmac: 91851690db523f3033aaa3788143b6d9c51713919046cd51a546304c8c62d1f0

...
