---
kind: pipeline
type: ssh
name: Test

server:
  host: martha.r
  user: ci
  ssh_key:
    from_secret: SSH_KEY

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: run tests
  commands:
  - pytest -s ./tests
trigger:
  branch:
  - main
  event:
  - push
  - pull_request

---
kind: signature
hmac: 0e3b46ca414f8f949406a2cb3a4455d88c84f09ca51a873de9c71b8941d8a2af

...
