---
kind: pipeline
type: ssh
name: Test

server:
  host: martha.r
  user: ci
  ssh_key:
    from_secret: SSH_KEY

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: run tests
  commands:
  - nix-shell ./ci.nix --run 'pytest -n $(nproc --ignore=2) -s ./tests'
trigger:
  event:
  - push

---
kind: signature
hmac: d0ae33a07c91c6d2c26ea980453f298400ad6e3ef82e1c869a0588298448620a

...
