---
kind: pipeline
type: ssh
name: Test

server:
  host: martha.r
  user: ci
  ssh_key:
    from_secret: SSH_KEY

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: run tests
  commands:
  - nix-shell ./ci.nix --run 'pytest -s ./tests'
trigger:
  event:
  - push

---
kind: signature
hmac: f76f9042f2f43346e512039664b2650bf4fbb38468f8b376cad80dff9b514542

...
