[package]
name = "vmsh"
version = "0.1.0"
authors = [
  "Jörg Thalheim <joerg@thalheim.io>",
  "Pogobanane <aenderboy@gmx.de>"
]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
tempfile = "3"

[workspace]
members = ["src/virtio"]

[dependencies]
clap = "2"
nix = "0.20.*"
libc = "0.2.*"
bcc = "0.0.*"
simple-error = "0.2.*"
kvm-bindings = "0.3.*"
virtio = { path = "src/virtio" }

# src/device/ deps:
vm-virtio = { git = "https://github.com/rust-vmm/vm-virtio.git", features = ["backend-stdio"] } # does no kvm operations
vm-device = { git = "https://github.com/rust-vmm/vm-device" } # does no kvm operations

# src/device/virtio/ deps:
event-manager = { version = "0.2.0", features = ["remote_endpoint"] }
vmm-sys-util = "0.6.1" # only for its ::eventfd::EventFd
vm-memory = { version = "0.5.0", features = ["backend-mmap"] }
log = "0.4.6"

# patches:

# We need these patches until the latest changes get released.
[patch.crates-io]
event-manager = { git = "https://github.com/rust-vmm/event-manager.git", rev = "19ddbaa" }

[patch."https://github.com/rust-vmm/vm-virtio.git"]
vm-virtio = { git = "https://github.com/alexandruag/vm-virtio.git", branch = "proto_wip4" }
