[package]
name = "vmsh"
version = "0.1.0"
authors = [
  "Jörg Thalheim <joerg@thalheim.io>",
  "Pogobanane <aenderboy@gmx.de>"
]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
tempfile = "3"

[workspace]
members = ["src/virtio"]

[dependencies]
argparse = "0.2.*"
nix = "0.19.*"
libc = "0.2.*"
bcc = "0.0.*"
ctrlc = "3.1.*"
simple-error = "0.2.*"
kvm-bindings = "0.3.*"
virtio = { path = "src/virtio" }
vm-virtio = { git = "https://github.com/rust-vmm/vm-virtio.git", features = ["backend-stdio"] }
vm-device = { git = "https://github.com/rust-vmm/vm-device" }
