[package]
name = "vmsh"
version = "0.1.0"
authors = [
  "Jörg Thalheim <joerg@thalheim.io>",
  "Pogobanane <aenderboy@gmx.de>"
]
edition = "2018"
default-run = "vmsh"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
tempfile = "3"

[workspace]
members = ["src/virtio"]
exclude = ["src/stage1", "src/stage2"]

[dependencies]
clap = "2"
nix = "0.21.*"
libc = "0.2.*"
bcc = "0.0.*"
simple-error = "0.2.*"
kvm-bindings = "0.4.*"
virtio = { path = "src/virtio" }
env_logger = "0.8.*"
lazy_static = "*"
container-pid = "0.1.0"

# src/device/ deps:
# Switch back to upstream, once https://github.com/rust-vmm/vm-virtio/pull/56 is merged
vm-virtio = { git = "https://github.com/Mic92/vm-virtio.git", features = ["backend-stdio"], rev = "8a8270924ad691232f9f9b3157e66fddd7ba9975"} # does no kvm operations
#vm-virtio = { path = "src/vm-virtio", features = ["backend-stdio"] }
vm-device = { git = "https://github.com/rust-vmm/vm-device", rev = "989c315712b80a538331fe05716323f2f64abf2e" } # does no kvm operations

# src/device/virtio/ deps:
event-manager = { version = "0.2.1", features = ["remote_endpoint"] }
vmm-sys-util = "0.8.0" # only for its ::eventfd::EventFd
vm-memory = { version = "0.5.0", features = ["backend-mmap"] }
log = "0.4.6"

[patch.crates-io]
# no atomicity support
# vm-memory = { git = "https://github.com/pogobanane/vm-memory.git", rev = "ecf1d8e0fd765759559c586d83760dfaf9812a8c", features = ["backend-mmap"] }
# atomicity support
vm-memory = { git = "https://github.com/pogobanane/vm-memory.git", rev = "06d9fcc2b025c92eed2a56e948d6708a3b144b07", features = ["backend-mmap"] }
#vm-memory = { path = "../vm-memory", features = ["backend-mmap"] }
