[package]
name = "stage1-interface"
version = "0.1.0"
authors = ["Jörg Thalheim <joerg@thalheim.io>"]
edition = "2018"
license = "MIT"

[dependencies]
chlorine = { version = "1.0.10", features = ["int_extras"] }
