[package]
name = "stage2"
version = "0.1.0"
authors = ["Jörg Thalheim <joerg@thalheim.io>"]
edition = "2018"
license = "MIT"

[dependencies]
nix = "0.24.1"
libc = "0.2.126"
simple-error = "0.2.3"
ioutils = { path = "../ioutils" }
