[package]
name = "stage2"
version = "0.1.0"
authors = ["Jörg Thalheim <joerg@thalheim.io>"]
edition = "2018"
license = "MIT"

[dependencies]
nix = "0.26.2"
libc = "0.2.144"
simple-error = "0.3.0"
ioutils = { path = "../ioutils" }
