[package]
name = "stage2"
version = "0.1.0"
authors = ["Jörg Thalheim <joerg@thalheim.io>"]
edition = "2018"
license = "MIT"

[dependencies]
nix = "0.21.*"
libc = "0.2.*"
simple-error = "0.2.*"
container-pid = "0.1.0"
ioutils = { path = "../ioutils" }
