[package]
name = "stage1"
version = "0.1.0"
authors = ["Jörg Thalheim <joerg@thalheim.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = { version = "0.2.*" }

[lib]
crate_type = ["staticlib"]

[profile.dev]
panic = "abort"
lto = true
opt-level = "z"

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
